#! /bin/sh

# Get colors from .Xresources
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

# Configurations
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap					12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

# Window rules

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a URxvt desktop='^1' follow=on focus=on

# 2 > file manager
bspc rule -a Thunar desktop='^2' follow=on focus=on

# 3 > web
bspc rule -a Firefox desktop='^3' follow=on focus=on

# 4 > code
bspc rule -a VSCodium desktop='^4' follow=on focus=on

# 5 > code
bspc rule -a notion-snap desktop='^5' follow=on focus=on

# special rules
bspc rule -a Firefox:Places state=floating follow=on focus=on

# Autostart

# x cursor fix
xsetroot -cursor_name left_ptr &

# launch keybindings daemon
killall -9 sxhkd
sxhkd &

# wallpaper
~/.fehbg &

# bar
killall -9 polybar
~/.config/polybar/launch.sh &

# compositor
killall -9 picom
picom -b &
