#!/usr/bin/env bash

EXNOTIFY_SEND="${HOME}/.scripts/notify-send/notify-send.sh"
DEFAPPS_EXEC="${HOME}/.scripts/default-apps/launch"

{ type -p {"mpd","mpc"} || type -p {"spotify","playerctl"}; } &> /dev/null || exit 1

CURRENT_MUSICPL="$($DEFAPPS_EXEC -g musicpl)"

if [[ "$CURRENT_MUSICPL" = "mpd" ]]; then
    prev="mpc -p 6601 -q prev"
    toggle="mpc -p 6601 -q toggle"
    stop="mpc -p 6601 -q stop"
    next="mpc -p 6601 -q next"
    status="mpc -p 6601 status"
    title="$(mpc -p 6601 --format '[%title%|%file%]' current)"
elif [[ "$CURRENT_MUSICPL" = "spotify" ]]; then
    prev="playerctl -p spotify previous"
    toggle="playerctl -p spotify play-pause"
    stop="playerctl -p spotify stop"
    next="playerctl -p spotify next"
    status="playerctl -p spotify status"
    title="$(playerctl -p spotify metadata -f '{{title}}')"
else
    prev=""
    toggle=""
    stop=""
    next=""
    status=""
    title="There is no mpd or spotify installed"
fi

case $1 in
    icon)       [[ "$($status)" = *"laying"* ]] && exec echo "" || exec echo ""
    ;;
    prev)       exec $($prev)
    ;;
    toggle)     exec $($toggle)
    ;;
    stop)       exec $($stop)
    ;;
    next)       exec $($next)
    ;;
    status)     exec echo "$($status)"
    ;;
    title)      exec echo "$title"
    ;;
    switchpl)   [[ "$($status)" = *"laying"* ]] && $($toggle) || :
                if [[ "$CURRENT_MUSICPL" != "mpd" ]]; then
                    sed -i 's_musicpl=".*"_musicpl="mpd"_' "$DEFAPPS_FILE"
                elif [[ "$CURRENT_MUSICPL" != "spotify" ]]; then
                    sed -i 's_musicpl=".*"_musicpl="spotify"_' "$DEFAPPS_FILE"
                fi && \
                exec "$EXNOTIFY_SEND" -u low -r 8888 -i "$NOTIF_MUSIC_ICON" "Music Player" "<span size='small'><u>$($DEFAPPS_EXEC -g musicpl)</u></span>\nSuccessfully set as default"
    ;;
esac; exit $?